cbt/urls.py
from django.urls import path
from . import views

app_name = "cbt"

urlpatterns = [
	
	path("setup-cbt/", views.SetupCbtView, name="setup_cbt"),
	path("take-cbt/<int:cbt_id>/", views.TakeCbtView, name="take_cbt"),
	path("complete-cbt/<int:cbt_id>/complete/", views.CompleteCbtView, name="complete_cbt"),

]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [

path("sign-in/", views.SignInView, name="sign_in"),
path("sign-up/", views.SignUpView, name="sign_up"),

path("profile/", views.ProfileView, name="profile"),

path("userlogout/", views.UserLogoutView, name="sign_out"),

path("whatever/", views.UserLogoutView, name="time_up_submit"),
path("", views.IndexView, name="index"),
path("about/", views.AboutView, name="about"),

]

study_aid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from main.sitemaps import StaticViewSitemap, StudyResourceSitemap
from django.conf import settings
from django.conf.urls.static import static


sitemaps = {
	"static": StaticViewSitemap,
	"study_resource": StudyResourceSitemap,

}


urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("app_user.urls")),
    path("", include("cbt.urls")),
    path("", include("compete.urls")),
    path("", include("main.urls")),
    path("", include("question.urls")),
    path("", include("study_resource.urls")),
    path("", include("theory.urls")),

	path("sitemap.xml", sitemap, {"sitemaps": sitemaps}),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

theory/urls.py
from django.urls import path
from . import views

app_name = "theory"

urlpatterns = [

	path("share-theory-question/", views.ShareTheoryView, name="share_theory"),
	path("edit-theory-question/", views.EditTheoryView, name="edit_theory"),

	path("theory/<str:category>/<str:level>/", views.AllTheoryView, name="all_theory"),
]

cbt/models.py
from django.db import models
from app_user.models import  AppUser
from question.models import Question
from theory.models import Theory

from django.utils import timezone


# Create your models here.


class Cbt(models.Model):
	title = models.CharField(max_length=500)
	cbt_slug = models.CharField(max_length=500, default="no slug")
	cbt_category = models.CharField(max_length=500)
	cbt_level = models.CharField(max_length=500)

	duration = models.CharField(max_length=500)
	
	app_user = models.ForeignKey(AppUser, on_delete=models.CASCADE)

	questions = models.ManyToManyField(Question, through="CbtQuestionConnector")
	theorys = models.ManyToManyField(Theory, through="CbtTheoryConnector")


	actual_score = models.IntegerField(default=0)
	total_score = models.IntegerField(default=0)
	percentage = models.IntegerField(default=0)

	corrections = models.TextField()

	status = models.BooleanField(default=False)

	pub_date = models.DateTimeField(default=timezone.now)

	def __str__(self):
		#return self.cart_id
		return str(self.title)



class CbtQuestionConnector(models.Model):
	cbt = models.ForeignKey(Cbt, on_delete=models.CASCADE)
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)


class CbtTheoryConnector(models.Model):
	cbt = models.ForeignKey(Cbt, on_delete=models.CASCADE)
	theory = models.ForeignKey(Theory, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)







class Result(models.Model):
	#app_user = models.ForeignKey(AppUser, on_delete=models.CASCADE)
	
	app_user_slug = models.CharField(max_length=100, default="none")

	cbt_id = models.CharField(max_length=100, default="none")
	cbt_title = models.CharField(max_length=100, default="none")
	cbt_type = models.CharField(max_length=100, default="none")
	cbt_slug = models.CharField(max_length=100, default="none")

	answers = models.CharField(max_length=100, default="none")
	response_theory = models.TextField(default="none")

	score = models.IntegerField(default=0)
	total = models.IntegerField(default=0)
	percentage = models.IntegerField(default=0)

	status = models.BooleanField(default=False)
	pub_date = models.DateTimeField(default=timezone.now)

	def __str__(self):
		#return self.cart_id
		return str(self.app_user.name)

cbt/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy

from question.models import Question
from theory.models import Theory
from cbt.models import Cbt, CbtQuestionConnector, CbtTheoryConnector
from app_user.models import AppUser
from main.views import ray_randomiser

import random
import string

# Create your views here.


def SetupCbtView(request):
	if request.user.is_active == True:
		if request.method == "POST":

		 	question_count = int(request.POST.get("question_count"))
		 	theory_count = int(request.POST.get("theory_count"))

		 	category = request.POST.get("category")
		 	level = request.POST.get("level")
		 	duration = request.POST.get("duration")

		 	app_user = AppUser.objects.get(user__pk=request.user.id)
		 	cbt_slug = ray_randomiser()

		 	title = "cbt(%s) for %s: %s" % (category, app_user, cbt_slug)

		 	cbt = Cbt.objects.create(app_user=app_user, title=title, cbt_slug=cbt_slug, cbt_level=level, cbt_category=category, duration=duration)
		 	cbt.save()

		 	questions = sorted(Question.objects.filter(category=category, level=level), key=lambda x: random.random())[:question_count]
		 	theorys = sorted(Theory.objects.filter(category=category, level=level), key=lambda x: random.random())[:theory_count]

		 	for item in questions:
		 		cbt_question =  CbtQuestionConnector(cbt=cbt, question=item)
		 		cbt_question.save()

		 	for item in theorys:
		 		cbt_theory =  CbtTheoryConnector(cbt=cbt, theory=item)
		 		cbt_theory.save()


		 	return HttpResponseRedirect(reverse("cbt:take_cbt", args=(cbt.id,)))

		else:
			context = {}
			return render(request, 'cbt/setup_cbt.html', context)


	else:
		return HttpResponse("Not Authorised!, Please contact NigTech(www.NigTech.net)")		





def TakeCbtView(request, cbt_id):
	cbt = Cbt.objects.get(id=cbt_id)

	questions = cbt.questions.all()
	counts = cbt.questions.count()
	count_list = []


	for i in range(counts):
		count_list.append(i+1)

	cbt_questions = zip(questions, count_list)

	if request.method == "POST":
		score = 0
		percentage = 0
		actual_score = 0
		real_score = 0

		answers = []
		answer_list = []
		for item, count in cbt_questions:
			val = "selected_answer_" + str(count)
			if request.POST.get(val):
				answers.append(request.POST.get(val))
			else:
				answers.append("x_x")

		for item in answers:
			answer_list.append(item.split("_")[1])


		for item, item2 in zip(cbt.questions.all(), answer_list):
			if item.real_answer == item2:
				actual_score += 1

		percentage = (actual_score/counts)*100

		#percentage, answer_list, actual_score, total_score, 

		cbt.actual_score = actual_score
		cbt.total_score = count
		cbt.percentage = percentage
		cbt.save()

		return HttpResponseRedirect(reverse("cbt:complete_cbt", args=(cbt.id,)))


	else:
		context = {"cbt": cbt, "cbt_questions": cbt_questions}#, "time_exam_link": time_exam_link, "time_student_id": time_student_id}#, "time_result_id": time_result_id}
		return render(request, "cbt/take_cbt.html", context)




def CompleteCbtView(request, cbt_id):
	cbt = Cbt.objects.get(id=cbt_id)

	theorys = cbt.theorys.all()
	counts = cbt.theorys.count()
	count_list = []

	for i in range(counts):
		count_list.append(i+1)

	cbt_theorys = zip(theorys, count_list)

	context = {"cbt": cbt, "cbt_theorys": cbt_theorys}
	return render(request, "cbt/complete_cbt.html", context)

cbt/templates/cbt/complete_cbt.html
{% extends 'main/base.html'%}
{% load static %}

{% block content %}

<style type="text/css">
    .ps-btn{
        background-color: #9a0052 !important;
        color: #fff;
        transition: 0.25s;
    }
	.ps-btn:hover{
        background-color: #ed017f !important;
   		color: #000000 !important;
   		transition: 0.25s;
    }
    .ps-btn-success{
        background-color: #ed017f !important;
        color: #fff;
        transition: 0.25s;
    }
	.ps-btn-success:hover{
        background-color: #9a0052 !important;
   		color: #000000 !important;
   		transition: 0.25s;
    }
	.pagination .active a{
        background-color: #9a0052 !important;
        color: #fff !important;
    }
    .pagination a:hover{
       	background-color: #9a0052 !important;
        color: #fff !important;
    }
    
</style>

<div class="ps-my-account">
            <div class="container">
                <form class="ps-form--account ps-tab-root" action=""  method="post">
                    {% csrf_token %}
                    <ul class="ps-tab-list">
                        <li class="active"><a href="#sign-in">Congratulations</a></li>
                    </ul>
                    <div class="ps-tabs">
                        <div class="ps-tab active" id="sign-in">
                            <div class="ps-form__content" style="background: #c5c5c5">

                                <div class="form-group" >
                               <blockquote class="generic-blockquote" >
								<h4>You scored: {{ cbt.actual_score }} out of {{ cbt.total_score }}</h4>
								<h5 style="margin-bottom: 15px">Percentage: {{ cbt.percentage }}%</h5>
								<br>
							</blockquote>
                                    
                                </div>
                                
                            </div>
                            <div class="ps-form__footer">
                                
                                <ul class="ps-list--social">
                                    <li>
                                    <a class="ps-btn-success" href="{% url 'theory:all_theory' cbt.cbt_category cbt.cbt_level %}"><h5 style="color: #fff">See Theory Questions</h5></a>
                                </li>
                                    <li><a class="ps-btn" href="{% url 'main:index' %}"><h5 style="color: #fff">Complete CBT</h5></a></li>
                                    
                                </ul>
                            </div>
                        </div>
                        <div class="ps-tab" id="register">
                            <div class="ps-form__content">
                                <h5>Register An Account</h5>
                                <div class="form-group">
                                    <input class="form-control" type="text" placeholder="Username or email address">
                                </div>
                                <div class="form-group">
                                    <input class="form-control" type="text" placeholder="Password">
                                </div>
                                <div class="form-group submtit">
                                    <button class="ps-btn ps-btn--fullwidth">Login</button>
                                </div>
                            </div>
                            <div class="ps-form__footer">
                                <p>Connect with:</p>
                                <ul class="ps-list--social">
                                    <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a class="google" href="#"><i class="fa fa-google-plus"></i></a></li>
                                    <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a class="instagram" href="#"><i class="fa fa-instagram"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </form>




{% endblock %}

cbt/templates/cbt/setup_cbt.html
{% extends 'main/homebase.html' %}
{% load static %}
  


{% block content %}

<style type="text/css">
    .ps-btn{
        background-color: #9a0052 !important;
        color: #fff;
        transition: 0.25s;
    }
    .ps-btn:hover{
        background-color: #ed017f !important;
        color: #000000 !important;
        transition: 0.25s;
    }
    .pagination .active a{
        background-color: #9a0052 !important;
        color: #fff !important;
    }
    .pagination a:hover{
        background-color: #9a0052 !important;
        color: #fff !important;
    }
    
</style>
<div class="container">

    <div class="row">
        
    </div>

</div>

 <section class="ps-section--account ps-checkout">

    <div class="container">
                             

<div class="ps-section__content">
                    <form class="ps-form--checkout" method="post">
                        {% csrf_token %}
                        <div class="ps-form__content">
                            <div class="row">
                                
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                    <div class="ps-block--shipping">
                                        
                                        <h4>Setup Computer Based Test</h4>
                                        <div class="ps-block--payment-method">
                                            <div class="ps-tabs">
                                                <div class="ps-tab active" id="visa">
                                                    <form class="ps-form--visa" method="post">
                                                        {% csrf_token %} 
                                                        <div class="form-group">
                                                            <label>Number of Objective Questions</label>
                                                            <input name="question_count" class="form-control" type="text" placeholder="" required="required">
                                                        </div>
                                                        <div class="form-group">
                                                            <label>Number of Theory Questions</label>
                                                            <input class="form-control" type="text" placeholder=""
                                                            name="theory_count" required="required">
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-12">
                                                                <div class="form-group">
                                                                    <label></label>
                                                                    <div class="row">
                                                                        <div class="col-4">
                                                                            <div class="form-group">
                                                                                 <label>Category</label>
                                                                                <select name="category" class="form-control">
                                                                                    <option value="general">General</option>
                                                                                    <option value="waec">Waec</option>
                                                                                    <option value="jamb">Jamb</option>
                                                                                    <option value="neco">Neco</option>
                                                                                    <option value="gce">GCE</option>
                                                                                    <option value="gmat">Gmat</option>
                                                                                </select>
                                                                            </div>
                                                                        </div>
                                                                        <div class="col-4">

                                                                            <div class="form-group">
                                                                                 <label>Duration</label> 
                                                                                <input class="form-control" type="text" placeholder="duration" name="duration" required="required">
                                                                            </div>
                                                                        </div>
                                                                        <div class="col-4">

                                                                            <div class="form-group">
                                                                                  <label>Level</label>
                                                                                <select name="level" class="form-control">
                                                                                    <option value="simple">Simple</option>
                                                                                    <option value="intermediate">Intermediate</option>
                                                                                    <option value="hard">Hard</option>
                                                                                </select>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                
                                                            </div>
                                                            
                                                        </div>
                                                        <div class="form-group submit">
                                                            <button class="ps-btn ps-btn--fullwidth">Start Test!</button>
                                                        </div>
                                                    </form>
                                                </div>
                                                
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>



{% endblock %}

cbt/templates/cbt/take_cbt.html
{% extends 'main/cbt_base.html'%}
{% load static %}

{% block content %}


<style type="text/css">
    .btn-success{
        background-color: #9A0052;
        color: #fff;
    }
    .btn-success:hover{
        background-color: #ed017f;
        color: #000000;
    }
</style>


<!-- Start Faculty Area -->
<section class="faculty-area section-gap" style="margin-top: -65px; background-color: #fff">
    <div class="container">
        <div class="row justify-content-center">

        <div class="row xd-flex" style="justify-content: right; float: right;">
        
            </div>

        <form class="container" method="post" enctype="multipart/form-data">
            {% csrf_token %}
        {% if cbt_questions %}
            {% for item, count in cbt_questions %}
            <div class="col-lg-12" style="background-color: #f5f5f5; margin-bottom:">
                <br><br>
                
                    <div class="col-lg-10" style="align-items: center; margin: auto;">
                        <div class="section-title" style="align-items: center;"> 

                            <blockquote class="generic-blockquote" style="background: #fff">
                                <h1>Q{{ count }}:</h1>{{ item.title}}

                            </blockquote>
                            <br>
                            <div class="row  d-flex align-items-center">

                                <div class="col-lg-6 col-md-6 col-sm-12 single-faculty">
                                    <div class="thumb d-flex"  style="background: #fff; padding-left: 10px;">
                                        <label class="custom-checkbox">
                                            <input type="radio" name="selected_answer_{{ count }}" value="{{ count }}_a" style="margin-bottom: -10px; margin-left: 5px;">
                                            <span class="checkmark" style="text-align: center; text-transform: capitalize; font-size: 18px; padding-bottom: 10px">A</span>
                                        </label>
                                        <p style="margin-top: 15px; margin-left: 10px">
                                             {{ item.answer_a }}
                                        </p>
                                    </div>
                                </div>

                                <div class="col-lg-6 col-md-6 col-sm-12 single-faculty">
                                    <div class="thumb d-flex"  style="background: #fff; padding-left: 10px;">
                                        <label class="custom-checkbox">
                                            <input type="radio" name="selected_answer_{{ count }}" value="{{ count }}_b">
                                            <span class="checkmark" style="text-align: center; text-transform: capitalize; font-size: 18px; padding-bottom: 10px">B</span>
                                        </label>
                                        <p style="margin-top: 15px; margin-left: 10px">
                                             {{ item.answer_b }}
                                        </p>
                                    </div>
                                </div>
                                <br><br><br>
                                <div class="col-lg-6 col-md-6 col-sm-12 single-faculty">
                                    <div class="thumb d-flex"  style="background: #fff; padding-left: 10px;">
                                        <label class="custom-checkbox">
                                            <input type="radio" name="selected_answer_{{ count }}" value="{{ count }}_c">
                                            <span class="checkmark" style="text-align: center; text-transform: capitalize; font-size: 18px; padding-bottom: 10px;">C</span>
                                        </label>
                                        <p style="margin-top: 15px; margin-left: 10px">
                                             {{ item.answer_c }}
                                        </p>
                                    </div>
                                </div>
                                <br><br><br>

                                <div class="col-lg-6 col-md-6 col-sm-12 single-faculty">
                                    <div class="thumb d-flex"  style="background: #fff; padding-left: 10px;">
                                        <label class="custom-checkbox">
                                            <input type="radio" name="selected_answer_{{ count }}" value="{{ count }}_d">
                                            <span class="checkmark" style="text-align: center; text-transform: capitalize; font-size: 18px; padding-bottom: 10px">D</span>
                                        </label>
                                        <p style="margin-top: 15px; margin-left: 10px">
                                             {{ item.answer_d }}
                                        </p>
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>

                    <hr>
                    <br />


            {% endfor %}
        {% endif %}
    
        <div class="container"><a href="/">
         
         <button class="btn btn-success" type="submit" style="justify-content: left; float: left;">Proceed to Section B</button>
         <br><br>
     </div>

    </form>

        </div>
    </div>
    <br>
</section>


{% endblock %}