cbt/urls.py
from django.urls import path
from . import views

app_name = "cbt"

urlpatterns = [
	
	path("setup-cbt/", views.SetupCbtView, name="setup_cbt"),
	path("take-cbt/<int:cbt_id>/", views.TakeCbtView, name="take_cbt"),
	path("complete-cbt/<int:cbt_id>/complete/", views.CompleteCbtView, name="complete_cbt"),

]

compete/urls.py
from django.urls import path
from . import views

app_name = "compete"

urlpatterns = [

	path("setup-compete/", views.SetupCompeteView, name="compete"),
	path("result/", views.ResultView, name="result"),
	path("result-detail/<int:id>/", views.ResultDetailView, name="result_detail"),
	path("join-compete", views.JoinCompeteView, name="join_compete"),

]

study_aid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from main.sitemaps import StaticViewSitemap, StudyResourceSitemap
from django.conf import settings
from django.conf.urls.static import static


sitemaps = {
	"static": StaticViewSitemap,
	"study_resource": StudyResourceSitemap,

}


urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("app_user.urls")),
    path("", include("cbt.urls")),
    path("", include("compete.urls")),
    path("", include("main.urls")),
    path("", include("question.urls")),
    path("", include("study_resource.urls")),
    path("", include("theory.urls")),

	path("sitemap.xml", sitemap, {"sitemaps": sitemaps}),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

compete/models.py
from django.db import models
from app_user.models import  AppUser
from question.models import Question
from theory.models import Theory

from django.utils import timezone

# Create your models here.


class Compete(models.Model):
	title = models.CharField(max_length=500)
	compete_slug = models.CharField(max_length=500, default="no slug")
	compete_level = models.CharField(max_length=500, default="simple")
	compete_category = models.CharField(max_length=500)

	duration = models.CharField(max_length=500)
	
	app_user = models.ForeignKey(AppUser, on_delete=models.CASCADE)

	questions = models.ManyToManyField(Question, through="CompeteQuestionConnector")

	status = models.BooleanField(default=False)
	audience = models.CharField(max_length=500, default="private")

	pub_date = models.DateTimeField(default=timezone.now)

	def __str__(self):
		#return self.cart_id
		return str(self.title)


class CompeteQuestionConnector(models.Model):
	compete = models.ForeignKey(Compete, on_delete=models.CASCADE)
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)




class Result(models.Model):
	app_user = models.ForeignKey(AppUser, on_delete=models.CASCADE)

	compete_id = models.CharField(max_length=100, default="none")

	answers = models.CharField(max_length=100, default="none")
	response_theory = models.TextField(default="none")

	score = models.IntegerField(default=0)
	total = models.IntegerField(default=0)
	percentage = models.IntegerField(default=0)

	status = models.BooleanField(default=False)
	pub_date = models.DateTimeField(default=timezone.now)

	def __str__(self):
		#return self.cart_id
		return str(self.app_user.name)

compete/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy

from compete.models import *
from question.models import *
from app_user.models import AppUser
from main.views import ray_randomiser

import random
import string

# Create your views here.


def SetupCompeteView(request):
	if request.method == "POST":
		question_count = int(request.POST.get("question_count"))
		level = request.POST.get("level")
		category = request.POST.get("category")
		duration = request.POST.get("duration")
		audience = request.POST.get("audience")

		app_user = AppUser.objects.get(user__pk=request.user.id)
		compete_slug = ray_randomiser()

		title = "compete(%s) for %s: %s" % (category, app_user, compete_slug)

		compete = Compete.objects.create(app_user=app_user, title=title, compete_slug=compete_slug, compete_level=level, compete_category=category, duration=duration, audience=audience)
		compete.save()

		questions = sorted(Question.objects.filter(category=category, level=level), key=lambda x: random.random())[:question_count]

		for item in questions:
			compete_question =  CompeteQuestionConnector(compete=compete, question=item)
			compete_question.save()

		return HttpResponseRedirect(reverse("compete:compete"))


	else:
		context = {}
		return render(request, "compete/setup.html", context)


	


def ResultView(request):
	if request.method == "POST":
		pass


	else:
		app_user = AppUser.objects.get(user__pk=request.user.id)
		competes = Compete.objects.filter(app_user__pk=app_user.id)


		context = {"competes": competes}
		return render(request, "compete/result.html", context)



def JoinCompeteView(request):
	compete_slug = request.POST.get("compete_slug")
	if request.method == "POST":
		#compete_slug = request.POST.get("compete_slug")
		return HttpResponse(compete_slug)


	else:
		return HttpResponse(compete_slug)




def ResultDetailView(request, id):
	compete = Compete.objects.get(id=id)
	compete_id = compete.id

	app_user = AppUser.objects.get(user__pk=request.user.id)

	questions = compete.questions.all()
	counts = compete.questions.count()
	count_list = []


	for i in range(counts):
		count_list.append(i+1)

	compete_questions = zip(questions, count_list)


	if request.method == "POST":
		score = 0
		percentage = 0
		actual_score = 0
		real_score = 0

		answers = []
		answer_list = []
		for item, count in compete_questions:
			val = "selected_answer_" + str(count)
			if request.POST.get(val):
				answers.append(request.POST.get(val))
			else:
				answers.append("x_x")

		for item in answers:
			answer_list.append(item.split("_")[1])


		for item, item2 in zip(compete.questions.all(), answer_list):
			if item.real_answer == item2:
				actual_score += 1

		percentage = (actual_score/counts)*100

		result = Result.objects.create(app_user=app_user, compete_id=compete_id, 
		 score=actual_score, total=count, percentage=percentage) 
		result.save()

		return HttpResponse("Complete!!!")



	else:
		

		try:
			results = Result.objects.filter(compete_id=compete_id)
		except:
			results = None


		if results:
			context = {"results": results}
			return render(request, "compete/result_detail.html", context)


		else:
			context = {"compete": compete, "compete_questions": compete_questions}#, "time_exam_link": time_exam_link, "time_student_id": time_student_id}#, "time_result_id": time_result_id}
			return render(request, "compete/take_compete.html", context)


			

compete/templates/compete/result.html
{% extends 'main/homebase.html' %}
{% load static %}
      

{% block content %}

 <section class="ps-section--account ps-checkout">

    <div class="container">

  <div class="ps-top-categories">
            <div class="ps-container">
                <h3>Study Resources for you!</h3>
                <div class="row">
                {% if competes %}
                  {% for item in competes %}
                    <div class="col-xl-2 col-lg-4 col-md-4 col-sm-4 col-6 ">
                        <div class="ps-block--category"><a href="{% url 'compete:result_detail' item.id %}"></a><br /><img src="{% static 'main/img/categories/1.jpg' %}" alt="">
                           <p>{{ item.title }}</p>
                        </div>
                    </div>
                    {% endfor %}
                  {% else %}
                    <p>Sorry, Nothing Yet!</p>
                {% endif %}
                </div>
            </div>
        </div>
</div>


</section>


{% endblock %}

compete/templates/compete/result_detail.html
{% extends 'main/homebase.html' %}
{% load static %}
  


{% block content %}
<p>Your Result:</p>


{% if results %}
<ul>
	{% for item in results %}
		<li>Name:{{ item.app_user }}, {{ item.score }} out of {{ item.total }}. ({{ item.percentage }}%)</li>
	{% endfor %}
</ul>
{% endif %}

{% endblock %}

compete/templates/compete/setup.html
{% extends 'main/base.html' %}
{% load static %}
  


{% block content %}
{% include "main/header.html" %}
<style type="text/css">
    .ps-btn{
        background-color: #ed017f !important;
    }
    .ps-btn:hover{
        background-color: #9a0052 !important;
        color: #fff;
    }
</style>


 <section class="ps-section--account ps-checkout">

    <div class="container">
                             

<div class="ps-section__content">
                    <form class="ps-form--checkout" method="post">
                        {% csrf_token %}
                        <div class="ps-form__content">
                            <div class="row">
                                <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
                                    <div class="ps-block--shipping">
                                        <h4>Join Competition</h4>
                                        <div class="ps-block__content">
                                            <div class="ps-block--payment-method">
                                                <div class="ps-tabs">
                                                    <div class="ps-tab active" id="visa">
                                                        {% csrf_token %}
                                                        <form class="ps-form--visa" method="post">
                                                                                             
                                                            <div class="form-group">
                                                                <label>Enter Competition code</label>
                                                                <input name="compete_slug" class="form-control" type="text" placeholder="" required="required">
                                                            </div>
                                                            <div class="form-group submit">
                                                                <button class="ps-btn ps-btn--fullwidth">Join</button>
                                                            </div>
                                                        </form>
                                                    </div>
                                                </div> 
                                            </div>  
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-8 col-lg-8 col-md-12 col-sm-12 col-12">
                                    <div class="ps-block--shipping">
                                        
                                        <h4>Setup Competition</h4>
                                        <div class="ps-block--payment-method">
                                            <div class="ps-tabs">
                                                <div class="ps-tab active" id="visa">
                                                    <form class="ps-form--visa" method="post">
                                                        {% csrf_token %} 
                                                        <div class="form-group">
                                                            <label>Audience</label>
                                                            <input name="audience" class="form-control" type="text" placeholder="" required="required">
                                                        </div>
                                                        <div class="form-group">
                                                            <label>Number of Objective Questions</label>
                                                            <input class="form-control" type="text" placeholder=""
                                                            name="question_count" required="required">
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-8">
                                                                <div class="form-group">
                                                                    <label></label>
                                                                    <div class="row">
                                                                        <div class="col-6">
                                                                            <div class="form-group">
                                                                                <input class="form-control" type="text" placeholder="Category" name="category" required="required">
                                                                            </div>
                                                                        </div>
                                                                        <div class="col-6">

                                                                            <div class="form-group">
                                                                                 
                                                                                <input class="form-control" type="text" name="level" placeholder="level" required="required">
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                
                                                            </div>
                                                            <div class="col-4">
                                                                <div class="form-group">
                                                                    <label></label>
                                                                    <input class="form-control" type="text" placeholder="duration" name="duration" required="required">
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="form-group submit">
                                                            <button class="ps-btn ps-btn--fullwidth">Submit</button>
                                                        </div>
                                                    </form>
                                                </div>
                                                <div class="ps-tab" id="paypal"><a class="ps-btn" href="#">Proceed with Paypal</a></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
        


{% endblock %}

compete/templates/compete/take_compete.html
{% extends 'main/cbt_base.html'%}
{% load static %}

{% block content %}





<!-- Start Faculty Area -->
<section class="faculty-area section-gap" style="margin-top: -65px;">
	<div class="container">
		<div class="row justify-content-center">

	

		<form class="container" method="post" enctype="multipart/form-data">
            {% csrf_token %}
		{% if compete_questions %}
			{% for item, count in compete_questions %}
				
					<div class="col-lg-12">
						<div class="section-title">	

							<blockquote class="generic-blockquote" style="background: #fff">
								<h1>Q{{ count }}:</h1>{{ item.title}}

							</blockquote>
							<br>
							<div class="row  d-flex align-items-center">

								<div class="col-lg-12 col-md-6 col-sm-12 single-faculty">
									<div class="thumb d-flex">
										<label class="custom-checkbox">
											<input type="radio" name="selected_answer_{{ count }}" value="{{ count }}_a" style="margin-bottom: -10px">
											<span class="checkmark" style="text-align: center; text-transform: capitalize; font-size: 28px; padding-bottom: -10px">A</span>
										</label>
										<p style="margin-top: 15px; margin-left: 10px">
											 {{ item.answer_a }}
										</p>
									</div>
								</div>

								<div class="col-lg-12 col-md-6 col-sm-12 single-faculty">
									<div class="thumb d-flex">
										<label class="custom-checkbox">
											<input type="radio" name="selected_answer_{{ count }}" value="{{ count }}_b">
											<span class="checkmark" style="text-align: center; font-size: 28px;">B</span>
										</label>
										<p style="margin-top: 15px; margin-left: 10px">
											 {{ item.answer_b }}
										</p>
									</div>
								</div>

								<div class="col-lg-12 col-md-6 col-sm-12 single-faculty">
									<div class="thumb d-flex">
										<label class="custom-checkbox">
											<input type="radio" name="selected_answer_{{ count }}" value="{{ count }}_c">
											<span class="checkmark" style="text-align: center; text-transform: capitalize; font-size: 28px;">C</span>
										</label>
										<p style="margin-top: 15px; margin-left: 10px">
											 {{ item.answer_c }}
										</p>
									</div>
								</div>

								<div class="col-lg-12 col-md-6 col-sm-12 single-faculty">
									<div class="thumb d-flex">
										<label class="custom-checkbox">
											<input type="radio" name="selected_answer_{{ count }}" value="{{ count }}_d">
											<span class="checkmark" style="text-align: center; font-size: 28px;">D</span>
										</label>
										<p style="margin-top: 15px; margin-left: 10px">
											 {{ item.answer_d }}
										</p>
									</div>
								</div>

							</div>

						</div>
					</div>
					<hr>
					<br />


			{% endfor %}
		{% endif %}
	

		 <button class="btn btn-success" type="submit">Proceed to Section B</button>

	</form>

		</div>
	</div>
</section>


{% endblock %}