cbt/urls.py
from django.urls import path
from . import views

app_name = "cbt"

urlpatterns = [
	
	path("setup-cbt/", views.SetupCbtView, name="setup_cbt"),
	path("take-cbt/<int:cbt_id>/", views.TakeCbtView, name="take_cbt"),
	path("complete-cbt/<int:cbt_id>/complete/", views.CompleteCbtView, name="complete_cbt"),

]

compete/urls.py
from django.urls import path
from . import views

app_name = "compete"

urlpatterns = [

	path("setup-compete/", views.SetupCompeteView, name="compete"),
	path("result/", views.ResultView, name="result"),
	path("result-detail/<int:id>/", views.ResultDetailView, name="result_detail"),
	path("join-compete", views.JoinCompeteView, name="join_compete"),

]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [

path("sign-in/", views.SignInView, name="sign_in"),
path("sign-up/", views.SignUpView, name="sign_up"),

path("profile/", views.ProfileView, name="profile"),

path("userlogout/", views.UserLogoutView, name="sign_out"),

path("whatever/", views.UserLogoutView, name="time_up_submit"),
path("", views.IndexView, name="index"),
path("about/", views.AboutView, name="about"),

]

question/urls.py
from django.urls import path
from . import views

app_name = "question"

urlpatterns = [

	path("share-question/", views.ShareQuestionView, name="share_question"),
	path("edit-question/", views.EditQuestionView, name="edit_question"),

]

study_aid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from main.sitemaps import StaticViewSitemap, StudyResourceSitemap
from django.conf import settings
from django.conf.urls.static import static


sitemaps = {
	"static": StaticViewSitemap,
	"study_resource": StudyResourceSitemap,

}


urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("app_user.urls")),
    path("", include("cbt.urls")),
    path("", include("compete.urls")),
    path("", include("main.urls")),
    path("", include("question.urls")),
    path("", include("study_resource.urls")),
    path("", include("theory.urls")),

	path("sitemap.xml", sitemap, {"sitemaps": sitemaps}),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

study_resource/urls.py
from django.urls import path
from . import views

app_name = "study_resource"

urlpatterns = [
	
	path("setup-study/", views.SetupShareView, name="setup_study"),
	#path("study-select/", views.StudySelectView, name="study_select"),
	path("share-study-resource/", views.ShareResourceView, name="share_resource"),
	path("resource/<slug:slug>/", views.ResourceDetailView, name="resource_detail"),
	#path("contribute-to-ebook/<int:id>/", views.ContributeFileResourceView, name="contribute_ebook"),
	path("contribute-to-ebook/<int:id>/", views.ContributeEbookView, name="contribute_ebook"),
	path("contribute-to-image/<int:id>/", views.ContributeImageView, name="contribute_image"),
	path("contribute-to-video/<int:id>/", views.ContributeVideoView, name="contribute_video"),
	#path("contribute-to-resource/<int:id>/", views.ContributeResourceView, name="contribute_resource"),
	path("contribute-to-content/<int:id>/", views.ContributeContentView, name="contribute_content"),
	path("contribute-to-link/<int:id>/", views.ContributeLinkResourceView, name="contribute_link"),
	path("contribute-to-chat/<int:id>/", views.ContributeChatView, name="contribute_chat"),

	path("content-detail/<int:content_id>/", views.ContentDetailView, name="content_detail"),


]

theory/urls.py
from django.urls import path
from . import views

app_name = "theory"

urlpatterns = [

	path("share-theory-question/", views.ShareTheoryView, name="share_theory"),
	path("edit-theory-question/", views.EditTheoryView, name="edit_theory"),

	path("theory/<str:category>/<str:level>/", views.AllTheoryView, name="all_theory"),
]

main/models.py
from django.db import models

# Create your models here.

main/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password1 = forms.CharField(widget=forms.PasswordInput())
	password2 = forms.CharField(widget=forms.PasswordInput())
	class Meta():
		model = User
		fields = ("username", "password1", "password2")

main/views.py
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User

from .forms import UserForm

from app_user.models import AppUser
from study_resource.models import *

import random
import string


# Create your views here.

def SignInView(request):
	if request.method == "POST":
		username = request.POST.get("username")
		password = request.POST.get("password")
		user = authenticate(username=username, password=password)
		if user:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect(reverse("main:index"))
			else:
				return HttpResponse("Incorrect Login!")

		else:
			return HttpResponse("Incorrect Login!")
	else:
		context = {}
		return render(request, "main/sign_in.html", context)



def IndexView(request):
	if request.user.is_active == True:
		if request.method == "POST":
			pass

			
		else:
			study_resources = sorted(StudyResource.objects.all(), key=lambda x: random.random())[:10]

			ebooks = sorted(Ebook.objects.all(), key=lambda x: random.random())[:10]
			videos = sorted(Video.objects.all(), key=lambda x: random.random())[:10]
			contents = sorted(Content.objects.all(), key=lambda x: random.random())[:10]
			links = sorted(Link.objects.order_by("-pub_date"), key=lambda x: random.random())[:10]
			forums = sorted(StudyResource.objects.all(), key=lambda x: random.random())[:10]


			context = {"study_resources": study_resources, "links": links, "forums": forums,
			"videos": videos, "ebooks": ebooks, "contents": contents,}
			return render(request, "main/index.html", context)


	else:
		return HttpResponseRedirect(reverse("main:sign_up"))



def ProfileView(request):
	if request.user.is_active == True:

		app_user = AppUser.objects.get(user__pk=request.user.id)

		if request.method == "POST":
			username = request.POST.get("username")
			full_name = request.POST.get("full_name")
			phone = request.POST.get("phone")
			email = request.POST.get("email")
			bio = request.POST.get("bio")
			gender = request.POST.get("gender")
			location = request.POST.get("location")

			if username != "":
				app_user.user.username = username
			if full_name != "":
				app_user.full_name = full_name
			if phone != "":
				app_user.phone = phone
			if email != "":
				app_user.email = email
			if bio != "":
				app_user.bio = bio
			if bio != "":
				app_user.gender = gender
			if bio != "":
				app_user.location = location


			try:
				file = request.FILES["image"]
				app_user.image = file

			except:
				pass


			app_user.save()

			return HttpResponseRedirect(reverse("main:profile"))

		else:

			ebooks = Ebook.objects.filter(contributor=app_user.user.username)
			videos = Video.objects.filter(contributor=app_user.user.username)
			contents = Content.objects.filter(contributor=app_user.user.username)
			links = Link.objects.filter(contributor=app_user.user.username)
			images = Image.objects.filter(contributor=app_user.user.username)

			forums = Chat.objects.filter(contributor__pk=app_user.id)

			resources = StudyResource.objects.filter(creator__pk=app_user.id)

			context = {"app_user": app_user, "ebooks": ebooks, "videos": videos,
			"contents": contents, "links": links, "images": images, "forums": forums, "resources": resources}
			return render(request, "main/profile.html", context)


	else:
		return HttpResponseRedirect(reverse("main:sign_up"))






def SignUpView(request):
	if request.method == "POST":

		form = UserForm(request.POST or None, request.FILES or None)


		if request.POST.get("password2") != request.POST.get("password1"):
			return HttpResponse("Error!  -Please make sure both passwords are similar")
			
		else:
			try:
				AppUser.objects.get(user__username=request.POST.get("username"))
				return HttpResponse("Error!  -Username already taken, try another one!")

			except:
				user = form.save()
				user.set_password(request.POST.get("password1"))
				user.save()

				app_user = AppUser.objects.create(user=user)
				app_user.save()

				return HttpResponseRedirect(reverse("main:sign_in"))

	else:
		form = UserForm()
		return render(request, "main/sign_up.html", {"form": form})





def UserLogoutView(request):
	logout(request)
	return HttpResponseRedirect(reverse("main:sign_in"))





def AboutView(request):
	if request.method == "POST":
		pass

	else:
		context = {}
		return render(request, "main/about.html", context)






def ray_randomiser(length=6):
	landd = string.ascii_letters + string.digits
	return ''.join((random.choice(landd) for i in range(length)))

main/templates/main/about.html
dsjnd

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="author" content="">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <title>Study - Aid</title>
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,600,700&amp;amp;subset=latin-ext" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'main/plugins/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/fonts/Linearicons/Linearicons/Font/demo-files/demo.css' %}">
    <link rel="stylesheet" href="{% static 'main/plugins/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/plugins/owl-carousel/assets/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/plugins/owl-carousel/assets/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/plugins/slick/slick/slick.css' %}">
    <link rel="stylesheet" href="{% static 'main/plugins/nouislider/nouislider.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/plugins/lightGallery-master/dist/css/lightgallery.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/plugins/jquery-bar-rating/dist/themes/fontawesome-stars.css' %}">
    <link rel="stylesheet" href="{% static 'main/plugins/select2/dist/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/autopart.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/vendor.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/styles.css' %}">
</head>
<style type="text/css">
    .current-menu-item:hover{
        background-color: #ed017f !important;
        color: #fff;
    }
    .mega-menu h4:hover{
        color: #ed017f !important;

    }
</style>
<body>
    
    <div class="ps-panel--sidebarx" id="cart-mobile" >
        
        
    </div>
    
    <div class="navigation--list" style="background-color: #9a0052 !important; color: #fff">
        <div class="navigation__content"><a class="navigation__item ps-toggle--sidebar" href="#menu-mobile"><i class="icon-menu"></i><span> Menu</span></a>
        <a class="navigation__item ps-toggle--sidebarm" href="{% url 'main:profile' %}"><i class="icon-user"></i><span> Profile</span></a>

        <a class="navigation__item" href="/"><i class="icon-home"></i><span> Home</span></a>

        <a class="navigation__item ps-toggle--sidebar" href="#search-sidebar"><i class="icon-magnifier"></i><span> Search</span></a>

        <a class="navigation__item" href="{% url 'main:sign_out' %}"><i class="icon-lock"></i><span> Log Out</span></a></div>

    </div>
    <div class="ps-panel--sidebar" id="search-sidebar" style="background-color: #fff;">
        <div class="ps-panel__header" style="background-color: #9a0052 !important;">
            <form class="ps-form--search-mobile" method="post" action="/search">
                    {% csrf_token %}
                <div class="form-group--nest">
                    <input name="query" class="form-control" type="text" placeholder="Enter any topic/subject/course...">
                    <button><i class="icon-magnifier"></i></button>
                </div>
            </form>
        </div>
        <div class="navigation__content"></div>
    </div>
    <div class="ps-panel--sidebar" id="menu-mobile" >
        <div class="ps-panel__header" style="background-color: #9a0052 !important;">
            <h3>Menu</h3>
        </div>
        <div class="ps-panel__content">
            <ul class="menu--mobile">
                <li class="menu-item-has-children"><a href="/">Home</a>
                    <ul class="menu--mobile">
                        <li class="current-menu-item menu-item-has-children"><a href="{% url 'cbt:setup_cbt' %}">CBT</a>
                        </li>
                        <li class="current-menu-item menu-item-has-children"><a href="{% url 'study_resource:setup_study' %}">Study</a>
                        </li>
                        <li class="current-menu-item menu-item-has-children"><a href="{% url 'compete:compete' %}">Compete</a>
                        </li>
                         <li class="current-menu-item menu-item-has-children"><a href="{% url 'question:share_question' %}">Obj Question</a>
                        </li>
                        <li class="current-menu-item menu-item-has-children"><a href="{% url 'question:share_question' %}">Theory Question</a>
                        </li>
                        <li class="current-menu-item menu-item-has-children"><a href="{% url 'study_resource:share_resource' %}">Share Resource</a>
                        </li>
                    </ul>
                            
                
                    </div>
                </li>
            </ul>
        </div>
    </div>

    
    
{% block content %}

{% endblock %}




    <footer class="ps-footer">
        <div class="ps-container">
            <div class="ps-footer__widgets">
               
            </div>
            
            <div class="ps-footer__copyright" style="">
                <p>© 2021 Nigtech.net. All Rights Reserved</p>
                
            </div>
        </div>
    </footer>
    <div id="back2top"><i class="pe-7s-angle-up"></i></div>
    <div class="ps-site-overlay"></div>
    <div id="loader-wrapper">
        <div class="loader-section section-left"></div>
        <div class="loader-section section-right"></div>
    </div>
    <div class="ps-search" id="site-search"><a class="ps-btn--close" href="#"></a>
        <div class="ps-search__content">
            <form class="ps-form--primary-search" action="do_action" method="post">
                <input class="form-control" type="text" placeholder="Search for...">
                <button><i class="aroma-magnifying-glass"></i></button>
            </form>
        </div>
    </div>
    
    <script src="{% static 'main/plugins/jquery.min.js' %}"></script>
    <script src="{% static 'main/plugins/nouislider/nouislider.min.js' %}"></script>
    <script src="{% static 'main/plugins/popper.min.js' %}"></script>
    <script src="{% static 'main/plugins/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'main/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'main/plugins/imagesloaded.pkgd.min.j' %}s"></script>
    <script src="{% static 'main/plugins/masonry.pkgd.min.js' %}"></script>
    <script src="{% static 'main/plugins/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'main/plugins/jquery.matchHeight-min.js' %}"></script>
    <script src="{% static 'main/plugins/slick/slick/slick.min.js' %}"></script>
    <script src="{% static 'main/plugins/jquery-bar-rating/dist/jquery.barrating.min.js' %}"></script>
    <script src="{% static 'main/plugins/slick-animation.min.js' %}"></script>
    <script src="{% static 'main/plugins/lightGallery-master/dist/js/lightgallery-all.min.js' %}"></script>
    <script src="{% static 'main/plugins/sticky-sidebar/dist/sticky-sidebar.min.js' %}"></script>
    <script src="{% static 'main/plugins/select2/dist/js/select2.full.min.js' %}"></script>
    <script src="{% static 'main/plugins/gmap3.min.js' %}"></script>
    <script src="{% static 'main/js/mains.js' %}"></script>
<!-- style switcher js -->
<script src="{% static 'main/js/style-switcher.js' %}"></script>
    <!-- custom scripts-->
    <script src="{% static 'main/js/main.js' %}"></script>
</body>

</html>

main/templates/main/header.html
{% load static %}
<header class="header header--1" data-sticky="true">
        <div class="header__top" style="background-color: #ed017f !important">
            <div class="ps-container">
                <div class="header__left">
                    <div class="menu--product-categories">
                        <div class="menu__toggle"><i class="icon-menu"></i><span> Study Aid</span></div>
                        <div class="menu__content">
                            <ul class="menu--dropdown">
                                <ul class="menu--dropdown">
                                <li class="current-menu-item "><a href="{% url 'cbt:setup_cbt' %}"><i class="icon-book2"></i>  Computer Based Test</a>
                                </li>
                                <li class="current-menu-item "><a href="{% url 'study_resource:setup_study' %}"><i class="icon-book2"></i>  Study</a>
                                </li>
                                <li class="current-menu-item "><a href="{% url 'compete:compete' %}"><i class="icon-book2"></i>  Compete</a>
                                </li>
                                <li class="current-menu-item "><a href="{% url 'question:share_question' %}"><i class="icon-book2"></i> Objective Questions</a></li>
                                <li class="current-menu-item "><a href="{% url 'theory:share_theory' %}"><i class="icon-book2"></i> Theory Questions</a></li>
                                <li class="current-menu-item "><a href="{% url 'study_resource:share_resource' %}"><i class="icon-book2"></i> Resource</a></li>
                            </ul>
                            </ul>
                        </div>
                    </div><a class="ps-logo" href="/"><img src="{% static 'main/img/logo_light.png' %}" alt=""></a>
                </div>
                <div class="header__center">
                    <form class="ps-form--quick-search" method="post" action="/search">
                        {% csrf_token %}
                        <input class="form-control" type="text" name="query" placeholder="Enter any topic/subject/course...">
                        <button>Search</button>
                    </form>
                </div>

                <div class="header__right">
                    <div class="header__actions">
                        
                        <div class="ps-block--user-header">
                            <div class="ps-block__left"><i class="icon-user"></i></div>
                            <div class="ps-block__right">
                                
                                <a href="{% url 'main:profile' %}">Profile</a>
                                <a href="{% url 'main:sign_out' %}">Logout</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <nav class="navigation" style="background-color: #9a0052 !important;">
            <div class="ps-container">
                <div class="navigation__left">
                    <div class="menu--product-categories">
                        <div style="color: #fff !important" class="menu__toggle"><i class="icon-menu"></i><span style="color: #fff !important"> Study Aid</span></div>
                        <div class="menu__content" >
                            <ul class="menu--dropdown">
                                <li class="current-menu-item "><a href="{% url 'cbt:setup_cbt' %}"><i class="icon-book2"></i>  Computer Based Test</a>
                                </li>
                                
                                <li class="current-menu-item "><a href="{% url 'study_resource:setup_study' %}"><i class="icon-book2"></i>  Study</a>
                                </li>

                                <li class="current-menu-item "><a href="{% url 'compete:compete' %}"><i class="icon-book2"></i>  Compete</a>
                                </li>
                                <li class="current-menu-item "><a href="{% url 'question:share_question' %}"><i class="icon-book2"></i> Objective Questions</a></li>
                                <li class="current-menu-item "><a href="{% url 'theory:share_theory' %}"><i class="icon-book2"></i> Theory Questions</a></li>
                                <li class="current-menu-item "><a href="{% url 'study_resource:share_resource' %}"><i class="icon-book2"></i> Resource</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="navigation__right">
                    <ul class="menu">
                        <li class=" has-mega-menu"><span>
                        </li>
                        <li class=" has-mega-menu"><span>
                        </li>
                        <li class=""><a href="{% url 'main:index' %}" style="color: #fff !important">Home</a></li>
                        <li class=" has-mega-menu"><span></li>
                        <li class="menu-item-has-children has-mega-menu"><a href="#" style="color: #fff !important">Menu</a><span class="sub-toggle"></span>
                            <div class="mega-menu">
                                <div class="mega-menu__column">
                                    <h4>Menu<span class="sub-toggle"></span></h4>
                                    <ul class="ps-dropdown-menu">
                                    <li><a href="{% url 'cbt:setup_cbt' %}">CBT</a></li>
                                    <li><a href="{% url 'study_resource:setup_study' %}">Study</a></li>
                                    
                                </ul>
                                </div>
                            </div>
                        </li>
                         <li class=" has-mega-menu"><span></li>
                        <li class="menu-item-has-children has-mega-menu"><a href="#" style="color: #fff !important">Share</a><span class="sub-toggle"></span>
                            <div class="mega-menu">
                                <div class="mega-menu__column">
                                    <h4>Share<span class="sub-toggle"></span></h4>
                                    <ul class="ps-dropdown-menu">
                                    <li><a href="{% url 'question:share_question' %}">Obj Question</a></li>
                                    <li><a href="{% url 'theory:share_theory' %}">Theory Question</a></li>
                                    <li><a href="{% url 'study_resource:share_resource' %}">Resource</a></li>
                                </ul>
                                </div>
                            </div>
                        </li>
                        
                    </ul>
                    <ul class="navigation__extra">

                        <li>
                            <div class="ps-dropdown language"><a style="color: #fff !important" href=""><img src="{% static 'main/img/flag/en.png' %}" alt="">Logged in as {{ request.user.username }}</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <header class="header header--mobile" data-sticky="true">
        <div class="header__top" style="background-color: #ed017f;">
            <div class="header__left">
                
            </div>
            <div class="header__right">
                <ul class="navigation__extra">
                    
                    
                    <li>
                        <div class="ps-dropdown language"><a href="#"><img src="img/flag/en.png" alt="">English</a>
                            <ul class="ps-dropdown-menu">
                                <li><a href="#"><img src="img/flag/germany.png" alt=""> Germany</a></li>
                                <li><a href="#"><img src="img/flag/fr.png" alt=""> France</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="navigation--mobile" style="background-color: #9a0052;">
            <div class="navigation__left"><a class="ps-logo" href="/"><img src="{% static 'main/img/logo_light.png' %}" alt=""></a></div>
            <div class="navigation__right">
                <div class="header__actions">
                    
                    </div>
                    <div class="ps-block--user-header">
                            <div class="ps-block__left"><i class="icon-user"></i></div>
                            <div class="ps-block__right">
                                
                                <a href="{% url 'main:profile' %}">Profile</a>
                                <a href="{% url 'main:sign_out' %}">Logout</a>
                            </div>
                        </div>
                </div>
            </div>
        </div>
        <div class="ps-search--mobile" style="background-color: #ed017f !important;">
            <form class="ps-form--search-mobile" action="index.html" method="get">
                <div class="form-group--nest">
                    <input class="form-control" type="text" placeholder="Search something...">
                    <button><i class="icon-magnifier"></i></button>
                </div>
            </form>
        </div>
    </header>

main/templates/main/sign_in.html
{% extends 'main/base.html' %}
{% load static %}
  


{% block content %}
<style type="text/css">
    .ps-btn{
        background-color: #ed017f !important;
        color: #000000 !important;
    }
    .ps-btn:hover{
        background-color: #9a0052 !important;
        color: #fff !important;
    }
    .btn-success {
        background-color: #9a0052 !important;
        color: #fff !important;
        border: none;
    }
    .btn-success:hover{
        background-color: #ed017f !important;
        color: #000000 !important;
        border: none;
    }
    .btn-success a:hover{
        
        color: #000000 !important;
        border: none;
    }
</style>


<div class="ps-my-account">
            <div class="container">
                <form class="ps-form--account ps-tab-root" action=""  method="post">
                    {% csrf_token %}
                    <ul class="ps-tab-list">
                        <li class="active"><a href="#sign-in">Sign-in</a></li>
                    </ul>
                    <div class="ps-tabs">
                        <div class="ps-tab active" id="sign-in">
                            <div class="ps-form__content">
                                <h5>Log In Your Account</h5>
                                <div class="form-group">
                                    <input class="form-control" type="text" name="username" placeholder="Username" required="required">
                                </div>
                                <div class="form-group form-forgot">
                                    <input class="form-control" type="password" name="password" placeholder="Password" required="required"><a href="">Forgot?</a>
                                </div>
                                <div class="form-group">
                                    <div class="ps-checkbox">
                                        <input class="form-control" type="checkbox" id="remember-me" name="remember-me">
                                        <label for="remember-me">Rememeber me</label>
                                    </div>
                                </div>
                                <div class="form-group submtit">
                                    <button class="ps-btn ps-btn--fullwidth">Login</button>
                                </div>
                            </div>
                            <div class="ps-form__footer">
                                <p>Don't have an account?  <button class="btn btn-success"><a href="{% url 'main:sign_up' %}">Create Account</a></button></p>
                            </div>
                        </div>
                        <div class="ps-tab" id="register">
                            
                            
                        </div>
                    </div>
                </form>








{% endblock %}