cbt/urls.py
from django.urls import path
from . import views

app_name = "cbt"

urlpatterns = [
	
	path("setup-cbt/", views.SetupCbtView, name="setup_cbt"),
	path("take-cbt/<int:cbt_id>/", views.TakeCbtView, name="take_cbt"),
	path("complete-cbt/<int:cbt_id>/complete/", views.CompleteCbtView, name="complete_cbt"),

]

study_aid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from main.sitemaps import StaticViewSitemap, StudyResourceSitemap
from django.conf import settings
from django.conf.urls.static import static


sitemaps = {
	"static": StaticViewSitemap,
	"study_resource": StudyResourceSitemap,

}


urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("app_user.urls")),
    path("", include("cbt.urls")),
    path("", include("compete.urls")),
    path("", include("main.urls")),
    path("", include("question.urls")),
    path("", include("study_resource.urls")),
    path("", include("theory.urls")),

	path("sitemap.xml", sitemap, {"sitemaps": sitemaps}),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

study_resource/urls.py
from django.urls import path
from . import views

app_name = "study_resource"

urlpatterns = [
	
	path("setup-study/", views.SetupShareView, name="setup_study"),
	#path("study-select/", views.StudySelectView, name="study_select"),
	path("share-study-resource/", views.ShareResourceView, name="share_resource"),
	path("resource/<slug:slug>/", views.ResourceDetailView, name="resource_detail"),
	#path("contribute-to-ebook/<int:id>/", views.ContributeFileResourceView, name="contribute_ebook"),
	path("contribute-to-ebook/<int:id>/", views.ContributeEbookView, name="contribute_ebook"),
	path("contribute-to-image/<int:id>/", views.ContributeImageView, name="contribute_image"),
	path("contribute-to-video/<int:id>/", views.ContributeVideoView, name="contribute_video"),
	#path("contribute-to-resource/<int:id>/", views.ContributeResourceView, name="contribute_resource"),
	path("contribute-to-content/<int:id>/", views.ContributeContentView, name="contribute_content"),
	path("contribute-to-link/<int:id>/", views.ContributeLinkResourceView, name="contribute_link"),
	path("contribute-to-chat/<int:id>/", views.ContributeChatView, name="contribute_chat"),

	path("content-detail/<int:content_id>/", views.ContentDetailView, name="content_detail"),


]

study_resource/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone

from app_user.models import AppUser

# Create your models here.

class Chat(models.Model):
	title = models.CharField(max_length=500)
	chat = models.TextField()
	contributor = models.ForeignKey(AppUser, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)


class Content(models.Model):
	title = models.CharField(max_length=500)
	content = models.TextField()
	contributor = models.CharField(max_length=500, default="Anonymous")
	pub_date = models.DateTimeField(default=timezone.now)


class Ebook(models.Model):
	title = models.CharField(max_length=500)
	ebook = models.FileField(upload_to='resource/ebooks/', blank=True)
	contributor = models.CharField(max_length=500, default="Anonymous")
	pub_date = models.DateTimeField(default=timezone.now)


class Video(models.Model):
	title = models.CharField(max_length=500)
	video = models.FileField(upload_to='resource/videos/', blank=True)
	contributor = models.CharField(max_length=500, default="Anonymous")
	pub_date = models.DateTimeField(default=timezone.now)


class Audio(models.Model):
	title = models.CharField(max_length=500)
	audio = models.FileField(upload_to='resource/audios/', blank=True)
	contributor = models.CharField(max_length=500, default="Anonymous")
	pub_date = models.DateTimeField(default=timezone.now)



class Image(models.Model):
	title = models.CharField(max_length=500)
	image = models.FileField(upload_to='resource/images/', blank=True)
	contributor = models.CharField(max_length=500, default="Anonymous")
	pub_date = models.DateTimeField(default=timezone.now)



class Link(models.Model):
	title = models.CharField(max_length=500)
	link = models.CharField(max_length=500)
	contributor = models.CharField(max_length=500, default="Anonymous")
	pub_date = models.DateTimeField(default=timezone.now)



class StudyResource(models.Model):
	cover_image = models.FileField(upload_to='cover_image/images/', blank=True)
	title = models.CharField(max_length=500)
	description = models.CharField(max_length=500)

	study_level = models.CharField(max_length=500)
	study_category = models.CharField(max_length=500)

	chats = models.ManyToManyField(Chat, through="StudyResourceChatConnector")
	contents = models.ManyToManyField(Content, through="StudyResourceContentConnector")
	ebooks = models.ManyToManyField(Ebook, through="StudyResourceEbookConnector")
	videos = models.ManyToManyField(Video, through="StudyResourceVideoConnector")
	audios = models.ManyToManyField(Audio, through="StudyResourceAudioConnector")
	images = models.ManyToManyField(Image, through="StudyResourceImageConnector")
	links = models.ManyToManyField(Link, through="StudyResourceLinkConnector")

	creator = models.ForeignKey(AppUser, on_delete=models.CASCADE)
	slug = models.SlugField(unique=True, default="rayslug")
	pub_date = models.DateTimeField(default=timezone.now)

	
	def save(self, *args, **kwargs):
		var = self.title +"-" + str(self.pub_date)
		self.slug = slugify(var)
		super().save(*args, **kwargs)
		
	def get_absolute_url(self):
		return "/resource/%s/"%self.slug
		
	def __str__(self):
		return self.title



class StudyResourceChatConnector(models.Model):
	study_resource = models.ForeignKey(StudyResource, on_delete=models.CASCADE)
	chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)

class StudyResourceContentConnector(models.Model):
	study_resource = models.ForeignKey(StudyResource, on_delete=models.CASCADE)
	content = models.ForeignKey(Content, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)

class StudyResourceEbookConnector(models.Model):
	study_resource = models.ForeignKey(StudyResource, on_delete=models.CASCADE)
	ebook = models.ForeignKey(Ebook, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)


class StudyResourceVideoConnector(models.Model):
	study_resource = models.ForeignKey(StudyResource, on_delete=models.CASCADE)
	video = models.ForeignKey(Video, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)


class StudyResourceAudioConnector(models.Model):
	study_resource = models.ForeignKey(StudyResource, on_delete=models.CASCADE)
	audio = models.ForeignKey(Audio, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)


class StudyResourceImageConnector(models.Model):
	study_resource = models.ForeignKey(StudyResource, on_delete=models.CASCADE)
	image = models.ForeignKey(Image, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)


class StudyResourceLinkConnector(models.Model):
	study_resource = models.ForeignKey(StudyResource, on_delete=models.CASCADE)
	link = models.ForeignKey(Link, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)

study_resource/views.py
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy

from main.views import ray_randomiser

from study_resource.models import *
from app_user.models import AppUser

import random
import string

# Create your views here.


def SetupShareView(request):
	if request.user.is_active == True:
		if request.method == "POST":

		 	category = request.POST.get("category")
		 	level = request.POST.get("level")

		 	study_resources = sorted(StudyResource.objects.filter(study_category=category, study_level=level), key=lambda x: random.random())

		 	context = {"study_resources": study_resources}
		 	return render(request, 'study_resource/select_study.html', context)

		else:
			context = {}
			return render(request, 'study_resource/setup_study.html', context)


	else:
		return HttpResponseRedirect(reverse("main:sign_up"))	



def ShareResourceView(request):
	if request.user.is_active == True:
		if request.method == "POST":

			title = request.POST.get("title")
			description = request.POST.get("description")

			study_level = request.POST.get("level")
			study_category = request.POST.get("category")

			content = request.POST.get("content")
			link = request.POST.get("link")

			app_user = AppUser.objects.get(user__pk=request.user.id)
			creator = app_user


			study_resource = StudyResource.objects.create(creator=creator, title=title, description=description, study_level=study_level, study_category=study_category)


			if content != "":
				title = study_resource.title
				content = Content.objects.create(title=title, content=content, contributor=app_user.user.username)
				content.save()
				study_resource_content = StudyResourceContentConnector(study_resource=study_resource, content=content)
				study_resource_content.save()

			study_resource.save()


			return HttpResponseRedirect(reverse("main:index"))

			

		else:
			context = {}
			return render(request, "study_resource/share.html", context)
	else:
		return HttpResponseRedirect(reverse("main:sign_up"))


def ResourceDetailView(request, slug):
	#if request.user.is_active == True:
	study_resource = StudyResource.objects.get(slug=slug)
	context = {"study_resource": study_resource}
	return render(request, "study_resource/detail.html", context)

#	else:
#		return HttpResponseRedirect(reverse("main:sign_up"))

def ContentDetailView(request, content_id):
	if request.user.is_active == True:
		#resource_content = study_resource.contents.get(id=content_id)
		resource_content = Content.objects.get(id=content_id)

		#return HttpResponse(str(resource_content))

		context = {"resource_content": resource_content}
		return render(request, "study_resource/content_detail.html", context)

	else:
		return HttpResponseRedirect(reverse("main:sign_up"))


def ContributeVideoView(request, id):
	if request.user.is_active == True:
		study_resource = StudyResource.objects.get(id=id)

		if request.method == "POST":

			app_user = AppUser.objects.get(user__pk=request.user.id)
			contributor = app_user.user.username
			title = study_resource.title

			try:
				file = request.FILES["study_file"]
				video = Video.objects.create(title=title, video=file, contributor=contributor)
				video.save()

				study_resource_video = StudyResourceVideoConnector(study_resource=study_resource, video=video)
				study_resource_video.save()

			except:
				pass


			return HttpResponseRedirect(reverse("study_resource:contribute_video", args=(study_resource.id,)))


			

		else:
			context = {"study_resource": study_resource}
			return render(request, "study_resource/contribute_video.html", context)

	else:
		return HttpResponseRedirect(reverse("main:sign_up"))



def ContributeImageView(request, id):
	if request.user.is_active == True:
		study_resource = StudyResource.objects.get(id=id)

		if request.method == "POST":

			app_user = AppUser.objects.get(user__pk=request.user.id)
			contributor = app_user.user.username
			title = study_resource.title

			try:
				file = request.FILES["study_file"]
				image = Image.objects.create(title=title, image=file, contributor=contributor)
				image.save()

				study_resource_image = StudyResourceImageConnector(study_resource=study_resource, image=image)
				study_resource_image.save()

			except:
				pass


			return HttpResponseRedirect(reverse("study_resource:contribute_image", args=(study_resource.id,)))


			

		else:
			context = {"study_resource": study_resource}
			return render(request, "study_resource/contribute_image.html", context)

	else:
		return HttpResponseRedirect(reverse("main:sign_up"))


def ContributeEbookView(request, id):
	if request.user.is_active == True:
		study_resource = StudyResource.objects.get(id=id)

		if request.method == "POST":

			app_user = AppUser.objects.get(user__pk=request.user.id)
			contributor = app_user.user.username

			title = study_resource.title

			try:
				file = request.FILES["study_file"]
				ebook = Ebook.objects.create(title=title, ebook=file, contributor=contributor)
				ebook.save()

				study_resource_ebook = StudyResourceEbookConnector(study_resource=study_resource, ebook=ebook)
				study_resource_ebook.save()

			except:
				pass


			return HttpResponseRedirect(reverse("study_resource:contribute_ebook", args=(study_resource.id,)))

			

		else:
			context = {"study_resource": study_resource}
			return render(request, "study_resource/contribute_ebook.html", context)


	else:
		return HttpResponseRedirect(reverse("main:sign_up"))


def ContributeContentView(request, id):
	if request.user.is_active == True:
		study_resource = StudyResource.objects.get(id=id)

		if request.method == "POST":

			content = request.POST.get("content")

			app_user = AppUser.objects.get(user__pk=request.user.id)
			contributor = app_user.user.username

			title = study_resource.title
			
			if content != "":
				content = Content.objects.create(title=title, content=content, contributor=contributor)
				content.save()
				study_resource_content = StudyResourceContentConnector(study_resource=study_resource, content=content)
				study_resource_content.save()

			study_resource.save()


			return HttpResponseRedirect(reverse("study_resource:contribute_content", args=(study_resource.id,)))


		
		else:
			context = {"study_resource": study_resource}
			return render(request, "study_resource/contribute_content.html", context)


	else:
		return HttpResponseRedirect(reverse("main:sign_up"))


def ContributeLinkResourceView(request, id):
	if request.user.is_active == True:
		study_resource = StudyResource.objects.get(id=id)

		if request.method == "POST":


			link = request.POST.get("link")

			app_user = AppUser.objects.get(user__pk=request.user.id)
			contributor = app_user.user.username
			title = study_resource.title

			if link != "":
				link = Link.objects.create(title=title, link=link, contributor=contributor)
				link.save()
				study_resource_link = StudyResourceLinkConnector(study_resource=study_resource, link=link)
				study_resource_link.save()


			study_resource.save()


			return HttpResponseRedirect(reverse("study_resource:contribute_link", args=(study_resource.id,)))

			

		else:
			context = {"study_resource": study_resource}
			return render(request, "study_resource/contribute_to_links.html", context)



	else:
		return HttpResponseRedirect(reverse("main:sign_up"))




def ContributeChatView(request, id):
	if request.user.is_active == True:
		study_resource = StudyResource.objects.get(id=id)

		if request.method == "POST":

			chat = request.POST.get("chat")

			app_user = AppUser.objects.get(user__pk=request.user.id)
			contributor = app_user

			title = study_resource.title

			
			if chat != "":
				chat = Chat.objects.create(title=title, chat=chat, contributor=contributor)
				chat.save()
				study_resource_chat = StudyResourceChatConnector(study_resource=study_resource, chat=chat)
				study_resource_chat.save()

			study_resource.save()

			return HttpResponseRedirect(reverse("study_resource:contribute_chat", args=(study_resource.id,)))

		
		else:
			context = {"study_resource": study_resource}
			return render(request, "study_resource/contribute_chat.html", context)


	else:
		return HttpResponseRedirect(reverse("main:sign_up"))

study_resource/templates/study_resource/chat_forum.html
{% extends 'main/homebase.html' %}


{% load static %}
      

{% block content %}

<div class="ps-page--single ps-page--vendor">
        <section class="ps-store-list">
            <div class="container">
                
                <div class="ps-section__wrapper">
                    <div class="ps-section__left">
                        <aside class="widget widget--vendor">
                            <h3 class="widget-title">Product Search</h3>
                            <div class="form-group--icon">
                                <input class="form-control" type="text" placeholder="Search..."><i class="icon-magnifier"></i>
                            </div>
                        </aside>
                        <aside class="widget widget--vendor">
                            <h3 class="widget-title">Store Categories</h3>
                            <ul class="ps-list--arrow">
                                <li><a href="#">Interior</a></li>
                                <li><a href="#">Lighting</a></li>
                                <li class="menu-item-has-children"><a href="#">Exterior</a>
                                    <ul class="sub-menu ps-list--arrow">
                                        <li><a href="#"> Custom Grilles</a></li>
                                    </ul>
                                </li>
                                <li class="menu-item-has-children"><a href="#">Wheels & Tires</a>
                                    <ul class="sub-menu ps-list--categories">
                                        <li><a href="#"> Custom Grilles</a></li>
                                    </ul>
                                </li>
                                <li><a href="#">Factory Wheels</a></li>
                            </ul>
                        </aside>
                        <aside class="widget widget--vendor widget--open-time">
                            <h3 class="widget-title"><i class="icon-clock3"></i> Store Hours</h3>
                            <ul>
                                <li><strong>Monday:</strong><span>8:00 am - 6:00 pm</span></li>
                                <li><strong>Monday:</strong><span>8:00 am - 6:00 pm</span></li>
                                <li><strong>Monday:</strong><span>8:00 am - 6:00 pm</span></li>
                                <li><strong>Monday:</strong><span>8:00 am - 6:00 pm</span></li>
                                <li><strong>Monday:</strong><span>8:00 am - 6:00 pm</span></li>
                            </ul>
                        </aside>
                    </div>
                    <div class="ps-section__right">
                       <div class="ps-post-comments">
                <h3>Forum</h3>
                <div class="ps-block--comment">
                    <div class="ps-block__thumbnail"><img src="{% static 'main/img/5.jpg' %}" alt=""></div>
                    <div class="ps-block__content">
                        <h5>Jason bradley<small>MARCH 12, 2013 AT 1:17 PM</small></h5>
                        <p>Cras id nulla at metus congue auctor. Suspendisse auctor dictum orci quis interdum. Nullam et eleifend metus. Integer in est orci. Duis hendrerit ex metus, vel tempor sem aliquet nec. Donec ornare hend rerit bibendum.</p><a class="ps-block__reply" href="#">Reply</a>
                    </div>
                </div>
                <div class="ps-block--comment">
                    <div class="ps-block__thumbnail"><img src="{% static 'main/img/5.jpg' %}" alt=""></div>
                    <div class="ps-block__content">
                        <h5>Jared Erickson<small>MARCH 12, 2013 AT 1:17 PM</small></h5>
                        <p>Ut tellus ligula, interdum a interdum ut, egestas ut ipsum. Vivamus viverra consequat ipsum, nec auctor dolor eleifend sit amet. Nulla cursus fringilla metus a dictum</p><a class="ps-block__reply" href="#">Reply</a>
                        <div class="ps-block--comment">
                            <div class="ps-block__thumbnail"><img src="{% static 'main/img/5.jpg' %}" alt=""></div>
                            <div class="ps-block__content">
                                <h5>Chris Ames<small>MARCH 14, 2013 AT 8:01 AM</small></h5>
                                <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><a class="ps-block__reply" href="#">Reply</a>
                            </div>
                        </div>
                    </div>
                </div>
                <form class="ps-form--post-comment" action="do_action" method="post">
                    <h3>Leave a comment</h3>
                    <div class="form-group">
                        <textarea class="form-control" rows="8" placeholder="Your comment *" required></textarea>
                    </div>
                    <div class="row">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 ">
                            <div class="form-group">
                                <input class="form-control" type="text" placeholder="Your name*">
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 ">
                            <div class="form-group">
                                <input class="form-control" type="text" placeholder="your email*">
                            </div>
                        </div>
                        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 ">
                            <div class="form-group">
                                <input class="form-control" type="text" placeholder="your website">
                            </div>
                        </div>
                    </div>
                    <div class="form-group submit">
                        <button class="ps-btn">Post Comment</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
        </section>
    {% endblock %}

study_resource/templates/study_resource/content_detail.html
{% extends 'main/base.html' %}


{% load static %}
      

{% block content %}

{% include "main/header.html" %}

<section class="ps-section--account ps-checkout">

    <div class="container">
                             

<div class="ps-section__content">
                    
                        <div class="ps-form__content">
                            <div class="row">
                                
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                    <div class="ps-block--shipping">
                                        
                                        <div class="ps-block--payment-method">
                                            <div class="ps-tabs">
                                                <div class="ps-tab active" id="visa">
                                                        <div class="form-group" style="background-color: #fff; padding: 20px">
                                                           	 
                                                            <p>{{ resource_content.content }}</p>
                                                        </div>
                                                       
                                                <strong>contributed by: {{ resource_content.contributor }} </strong>       

                                
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </section>


{% endblock%}

study_resource/templates/study_resource/contribute.html
{% extends 'main/homebase.html' %}
{% load static %}
  


{% block content %}


<style type="text/css">
    .ps-btn{
        background-color: #ed017f !important;
    }
    .ps-btn:hover{
        background-color: #9a0052 !important;
        color: #fff;
    }
</style>

<section class="ps-section--account ps-checkout">

    <div class="container">
<div class="ps-section__content">
                    <form class="ps-form--checkout" method="post">
                        {% csrf_token %}
                        <div class="ps-form__content">
                            <div class="row">
                                
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                    <div class="ps-block--shipping">
                                        
                                        <h4>Contribute to ({{ study_resource.title }}) Resourcess</h4>
                                        <div class="ps-block--payment-method">
                                            <div class="ps-tabs">
                                                <form class="ps-form--visa" method="post">
                                                        {% csrf_token %}
                                                        <div class="row">
                                                            <div class="col-12">
                                                                <div class="form-group">
                                                                    <label></label>
                                                                    <div class="row">
                                                                       
                                                                    </div>

                                                                    <div class="form-group">
                                                                        <label>Content</label>
                                                                        <div class="form-group__content">
                                                                         <textarea name="content" class="form-control" rows="7" placeholder="Notes about your order, e.g. special notes for delivery."></textarea>
                                                                    </div>
                        
                                                        
                                                                    
                                                           <div class="row">
                                                            <div class="col-12">
                                                                <div class="form-group">
                                                                    <label></label>
                                                                    <div class="row">
                                                                        <div class="col-6">
                                                                            <div class="form-group">
                                                                                <label>File(Pdf,Video,Audio Book,Images)</label><br />
                                                                                <input type="file" name="study_file" class="form-control">
                                                                            </div>
                                                                        </div>
                                                                        <div class="col-6">

                                                                            <div class="form-group">
                                                                                 <label>Url Links</label>
                                                                                <input class="form-control" name="link" placeholder="Url Links" type="text">
                                                                            </div>
                                                                        </div>
                                                                    
                                                                    </div>
                                                                </div>
                                                                
                                                            </div>
                                                        </div>
                                                        <div class="form-group submit">
                                                            <button class="ps-btn ps-btn--fullwidth">Submit</button>
                                                        </div>

                                                    </form>
                                                </div>
                                            </div>
                                                                                                
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>

{% endblock %}

study_resource/templates/study_resource/select_study.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

{% include "main/header.html" %}

<section class="contact-section section" id="contact">           
    <div class="ps-top-categories">
        <div class="ps-container">
            <div class="section-title">
                <h2 data-heading="Resources">Filtered Resources</h2>
            </div>
            <div class="row">
            	{% for item in study_resources %}
                <div class="contact-item col-xl-3 col-lg-3 col-md-4 col-sm-4 col-6 ">
                    <div class="ps-block--category contact-item-inner outer-shadow inner-shadow hover-in-shadow"><a class="ps-block__overlay" href="{% url 'study_resource:resource_detail' item.slug %}"></a><img  style="height: 100px; width: 180" src="{% static 'main/img/Rb726b85a8621f4b7f0f50b5e8d25c01a.png' %}" alt="">
                        <p>{{ item.title }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>


        
 
{% endblock %}